create table TBL_VIDEOS(
  CODIGO_VIDEO INTEGER,
  NOMBRE_VIDEO VARCHAR2(500)
);


SELECT *
FROM TBL_USUARIOS;

SELECT B.NOMBRE_USUARIO, C.NOMBRE_CANCION
FROM TBL_CANCIONES_X_USUARIO A
INNER JOIN TBL_USUARIOS B
ON (A.CODIGO_USUARIO = B.CODIGO_USUARIO)
INNER JOIN TBL_CANCIONES C
ON (A.CODIGO_CANCION = C.CODIGO_CANCION)
WHERE A.CODIGO_USUARIO = :USER_ID;


DECLARE
  V_DESCRIPCION VARCHAR(500);
BEGIN
  SELECT DESCRIPCION
  INTO V_DESCRIPCION
  FROM TBL_CANCIONES 
  WHERE CODIGO_CANCION=:P1_CODIGO_CANCION;
  HTP.PRINT('<div style="color:#FF0000;background-color:#000000">'||V_DESCRIPCION||'</div>');
END;



SELECT CODIGO_CANCION AS CODIGO, NOMBRE_CANCION AS NOMBRE, '<img src="#APP_IMAGES#descarga.png">' TIPO
FROM TBL_CANCIONES
UNION ALL
SELECT CODIGO_VIDEO, NOMBRE_VIDEO, 'VIDEO' TIPO
FROM TBL_VIDEOS;
