---Mostrar todos los vuelos, aviones, y tripulacion de cada vuelo

SELECT *
FROM TBL_VUELOS;

SELECT *
FROM TBL_AVIONES;

SELECT *
FROM TBL_MARCAS;

SELECT *
FROM TBL_MODELOS;

SELECT *
FROM TBL_TRIPULACION;

SELECT *
FROM TBL_TRIPULACION_X_VUELOS;

-----------------
SELECT A.CODIGO_VUELO,
      A.FECHA_HORA_PARTIDA,
      A.FECHA_HORA_LLEGADA,
      A.CODIGO_AVION,
      B.REGISTRO,
      B.CANTIDAD_ASIENTOS,
      C.NOMBRE_MARCA,
      D.NOMBRE_MODELO,
      A.CODIGO_RUTA,
      E.CODIGO_TRIPULANTE,
      F.NOMBRE
FROM TBL_VUELOS A
INNER JOIN TBL_AVIONES B
ON (A.CODIGO_AVION = B.CODIGO_AVION)
INNER JOIN TBL_MARCAS C
ON (B.CODIGO_MARCA = C.CODIGO_MARCA)
INNER JOIN TBL_MODELOS D
ON (B.CODIGO_MODELO = D.CODIGO_MODELO)
INNER JOIN TBL_TRIPULACION_X_VUELOS E
ON (A.CODIGO_VUELO = E.CODIGO_VUELO)
INNER JOIN TBL_TRIPULACION F
ON (E.CODIGO_TRIPULANTE = F.CODIGO_TRIPULANTE)
ORDER BY A.CODIGO_VUELO;



--MOSTRAR LOS VUELOS CON TODOS LOS PUNTOS POR DONDE PASAN
--UTILIZANDO PRODUCTOS CARTESIANOS Y WHERE
SELECT *
FROM TBL_RUTAS;

SELECT *
FROM TBL_PUNTOS_X_RUTAS;

SELECT *
FROM TBL_PUNTO_ESCALA;

SELECT  A.CODIGO_VUELO,
        A.FECHA_HORA_PARTIDA,
        A.FECHA_HORA_LLEGADA,
        A.CODIGO_AVION,
        A.CODIGO_RUTA,
        B.ALIAS_RUTA,
        B.TIEMPO_PROMEDIO_MINUTOS,
        C.CODIGO_PUNTO,
        D.NOMBRE_PUNTO,
        D.LATITUD,
        D.LONGITUD,
        C.ORDEN_RUTA
FROM  TBL_VUELOS A,
      TBL_RUTAS B,
      TBL_PUNTOS_X_RUTAS C,
      TBL_PUNTO_ESCALA D
WHERE A.CODIGO_RUTA = B.CODIGO_RUTA
AND   B.CODIGO_RUTA = C.CODIGO_RUTA
AND   C.CODIGO_PUNTO = D.CODIGO_PUNTO
ORDER BY A.CODIGO_VUELO, C.ORDEN_RUTA;
