SET SERVEROUTPUT ON;
SELECT *
FROM TBL_VIDEOS;


DECLARE
  V_NOMBRE_VIDEO VARCHAR2(200);
  V_DESCRIPCION VARCHAR2(1000);
BEGIN
  SELECT NOMBRE_VIDEO, DESCRIPCION
  INTO V_NOMBRE_VIDEO, V_DESCRIPCION
  FROM TBL_VIDEOS
  WHERE CODIGO_VIDEO = 1;
  
  DBMS_OUTPUT.PUT_LINE('VIDEO: ' || V_NOMBRE_VIDEO);
  DBMS_OUTPUT.PUT_LINE('DESCRIPCION: ' || V_DESCRIPCION);
END;




DECLARE
  TYPE TIPO_VIDEO IS RECORD(
      NOMBRE_VIDEO VARCHAR2(200),
      DESCRIPCION_VIDEO VARCHAR2(1000)
  );
  V_VIDEO TIPO_VIDEO;
BEGIN
  V_VIDEO.NOMBRE_VIDEO := 'Gatitos adorables';
  V_VIDEO.DESCRIPCION_VIDEO := 'Muchos Gatitos adorables';
  
  DBMS_OUTPUT.PUT_LINE('VIDEO: ' || V_VIDEO.NOMBRE_VIDEO);
  DBMS_OUTPUT.PUT_LINE('DESCRIPCION: ' || V_VIDEO.DESCRIPCION_VIDEO);
  
  SELECT NOMBRE_VIDEO, DESCRIPCION
  INTO V_VIDEO
  FROM TBL_VIDEOS
  WHERE CODIGO_VIDEO = 1;
  
  DBMS_OUTPUT.PUT_LINE('VIDEO: ' || V_VIDEO.NOMBRE_VIDEO);
  DBMS_OUTPUT.PUT_LINE('DESCRIPCION: ' || V_VIDEO.DESCRIPCION_VIDEO);
END;


DECLARE 
  V_VIDEO TBL_VIDEOS%ROWTYPE;
BEGIN
  SELECT *
  INTO V_VIDEO
  FROM TBL_VIDEOS
  WHERE CODIGO_VIDEO = 1;
  
  DBMS_OUTPUT.PUT_LINE('VIDEO: ' || V_VIDEO.NOMBRE_VIDEO);
  DBMS_OUTPUT.PUT_LINE('VIDEO: ' || V_VIDEO.URL);
  DBMS_OUTPUT.PUT_LINE('VIDEO: ' || V_VIDEO.CANTIDAD_SHARES);
END;



---CURSORES:
---IMPLICITO: CURSORES ANONIMOS
---EXPLICITO: CURSORES CON NOMBRE


DECLARE 
  CURSOR C_VIDEOS IS SELECT * FROM youtube.TBL_VIDEOS;
  V_VIDEO C_VIDEOS%ROWTYPE;
BEGIN
  DBMS_OUTPUT.PUT_LINE ('<table>');
  DBMS_OUTPUT.PUT_LINE ('<tr><td>Nombre</td><td>Descripcion</td></tr>');
  OPEN C_VIDEOS;
  LOOP
    DBMS_OUTPUT.PUT_LINE ('<tr>');
    FETCH C_VIDEOS INTO V_VIDEO;
    EXIT WHEN C_VIDEOS%NOTFOUND;
    DBMS_OUTPUT.PUT_LINE ('<td>'||V_VIDEO.NOMBRE_VIDEO||'</td>');
    DBMS_OUTPUT.PUT_LINE ('<td>'||V_VIDEO.DESCRIPCION||'</td>');
    DBMS_OUTPUT.PUT_LINE ('</tr>');
  END LOOP;   
  DBMS_OUTPUT.PUT_LINE ('</table>');
  CLOSE C_VIDEOS;
END;




---CURSORES IMPLICITOS: (ANONIMOS), SOLO SE PUEDEN EJECUTAR CON UN FOR
BEGIN
  FOR V_VIDEO IN (SELECT * FROM youtube.TBL_VIDEOS) LOOP
    DBMS_OUTPUT.PUT_LINE('VIDEO: '||V_VIDEO.NOMBRE_VIDEO);
  END LOOP;
END;