SELECT A.EMPLOYEE_ID,
    A.FIRST_NAME || ' ' ||A.LAST_NAME AS EMPLOYEE_NAME,
    A.EMAIL,
    A.PHONE_NUMBER,
    A.HIRE_DATE,
    A.JOB_ID,
    B.JOB_TITLE,
    B.MAX_SALARY,
    B.MIN_SALARY,
    A.SALARY,
    A.COMMISSION_PCT,
    A.MANAGER_ID,
    C.FIRST_NAME ||' '|| C.LAST_NAME AS MANAGER_NAME,
    A.DEPARTMENT_ID,
    D.DEPARTMENT_NAME,
    E.STREET_ADDRESS,
    E.CITY,
    F.COUNTRY_NAME,
    F.REGION_ID,
    G.REGION_NAME
FROM HR.EMPLOYEES A
INNER JOIN HR.JOBS B
ON (A.JOB_ID = B.JOB_ID)
LEFT JOIN HR.EMPLOYEES C
ON (A.MANAGER_ID = C.EMPLOYEE_ID)
LEFT JOIN HR.DEPARTMENTS D
ON (A.DEPARTMENT_ID = D.DEPARTMENT_ID)
LEFT JOIN HR.LOCATIONS E
ON (D.LOCATION_ID = E.LOCATION_ID)
LEFT JOIN HR.COUNTRIES F
ON (E.COUNTRY_ID = F.COUNTRY_ID)
LEFT JOIN HR.REGIONS G
ON (F.REGION_ID = G.REGION_ID);



SELECT *
FROM DEPARTMENTS;

SELECT *
FROM LOCATIONS;

SELECT * 
FROM COUNTRIES;
---Cruces con productos cartesianos
SELECT A.EMPLOYEE_ID,
      A.FIRST_NAME || ' ' ||A.LAST_NAME AS EMPLOYEE_NAME,
      A.EMAIL,
      A.PHONE_NUMBER,
      A.HIRE_DATE,
      A.JOB_ID,
      B.JOB_TITLE,
      A.SALARY,
      A.COMMISSION_PCT,
      A.MANAGER_ID,
      A.DEPARTMENT_ID,
      C.FIRST_NAME ||' '|| C.LAST_NAME AS MANAGER_NAME,
      D.DEPARTMENT_NAME,
      E.CITY,
      E.STREET_ADDRESS,
      F.COUNTRY_NAME,
      G.REGION_NAME
FROM  EMPLOYEES A,
      JOBS B,
      EMPLOYEES C,
      DEPARTMENTS D,
      LOCATIONS E,
      COUNTRIES F,
      REGIONS G
WHERE A.JOB_ID = B.JOB_ID
AND  A.MANAGER_ID = C.EMPLOYEE_ID(+)
AND  A.DEPARTMENT_ID = D.DEPARTMENT_ID(+)
AND  D.LOCATION_ID = E.LOCATION_ID(+)
AND  E.COUNTRY_ID = F.COUNTRY_ID(+)
AND  F.REGION_ID = G.REGION_ID(+);


